/*!
 * filters-fix.js — v7 (Exact forte + Reset vicino Cerca)
 * - Filtri tecnici singoli a MATCH ESATTO (case-insensitive) *client-side*
 * - Reset "duro" accanto a Cerca che pulisce tutto e va in Home
 * - CERCA/APPLICA unificati, badge "Chiusa", scadenza rossa
 */
(function(){const LOG="[filters-fix v7]";const $=(s,ctx=document)=>ctx.querySelector(s);const $$=(s,ctx=document)=>Array.from(ctx.querySelectorAll(s));const norm=v=>String(v??'').toLowerCase().trim().replace(/\s+/g,' ');const has=v=>(v!=null&&String(v).trim()!=="");if(!window.sb){console.warn(LOG,"Supabase client mancante");return;}
(function(){const css=`#dataScadenza, input[name="dataScadenza"]{color:#dc3545!important;border-color:#dc3545!important}.text-scadenza-rossa{color:#dc3545!important}`;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);})();
function getFilters(){const F={};const map={q:"#q",note:"#filterNoteExact",battCollettore:"#f_battCollettore",lunghezzaAsse:"#f_lunghezzaAsse",lunghezzaPacco:"#f_lunghezzaPacco",larghezzaPacco:"#f_larghezzaPacco",punta:"#f_punta",numPunte:"#f_numPunte"};for(const[k,sel]of Object.entries(map)){const el=$(sel);if(!el)continue;const v=el.value;if(has(v))F[k]=v;}return F;}
function goHome(){const tryClick=(sel)=>{const b=$(sel);if(b){b.click();return true;}return false;};if(tryClick("#kpiTotBtn"))return;if(tryClick("#btnHome"))return;if(tryClick('[data-target="home"]'))return;const pages=["#page-home","#page-search","#page-detail","#page-archive","#page-mod"];const found=pages.map(s=>$(s)).filter(Boolean);found.forEach(p=>p.classList.add("d-none"));$("#page-home")?.classList.remove("d-none");window.scrollTo(0,0);}
function doReset(){$$("#page-search input,#page-search select,#page-search textarea").forEach(el=>{const t=el.type?el.type.toLowerCase():el.tagName.toLowerCase();if(t==="checkbox"||t==="radio")el.checked=false;else if(el.tagName==="SELECT"&&el.multiple)el.selectedIndex=-1;else if(el.tagName==="SELECT")el.selectedIndex=0;else el.value="";});$("#activeFilterBox")?.classList.add("d-none");if($("#activeFilterLabel"))$("#activeFilterLabel").innerHTML="";["#resBody","#listTableBody","#results","#resultsList"].forEach(sel=>{const el=document.querySelector(sel);if(!el)return;if(el.tagName==="TBODY"||el.tagName==="THEAD"||el.tagName==="TABLE"){el.innerHTML="";}else{el.classList.add("d-none");}});window.__SEARCH_ACTIVE__=false;if(window.__searchLock?.unlock)window.__searchLock.unlock();goHome();}
function buildQuery(F){let q=sb.from('records').select('*').limit(1000);const textFields=["note","battCollettore","punta"];textFields.forEach(k=>{if(has(F[k]))q=q.ilike(k,norm(F[k]));});const numFields=["lunghezzaAsse","lunghezzaPacco","larghezzaPacco","numPunte"];numFields.forEach(k=>{if(has(F[k]))q=q.eq(k,isNaN(Number(F[k]))?F[k]:Number(F[k]));});if(has(F.q)){const nx=norm(F.q);const cols=["descrizione","modello","cliente","telefono","email","note"];const ors=cols.map(c=>`${c}.ilike.${nx}`).join(",");q=q.or(ors);}try{q=q.order('dataApertura',{ascending:false});}catch(e){}return q;}
function clientExactFilter(rows,F){const n=s=>norm(s);const numEq=(a,b)=>{const na=Number(a),nb=Number(b);if(Number.isFinite(na)&&Number.isFinite(nb))return na===nb;return String(a)===String(b);};const keysText=["battCollettore","punta","note"];const keysNum=["lunghezzaAsse","lunghezzaPacco","larghezzaPacco","numPunte"];return rows.filter(r=>{if(has(F.q)){const nx=n(F.q);const cols=["descrizione","modello","cliente","telefono","email","note"];const okQ=cols.some(c=>n(r[c])===nx);if(!okQ)return false;}for(const k of keysText){if(has(F[k])&&n(r[k])!==n(F[k]))return false;}for(const k of keysNum){if(has(F[k])&&!numEq(r[k],F[k]))return false;}return true;});}
function decorateList(rows){try{const byId=new Map((rows||[]).map(r=>[String(r.id||""),r]));document.querySelectorAll('button[data-open]').forEach(btn=>{const id=String(btn.getAttribute('data-open')||"");const r=byId.get(id);if(r&&(r.statoPratica||"")==="Completata"){const td=btn.closest('td');if(td&&!td.querySelector('.badge-chiusa-v7')){const wrap=document.createElement('div');wrap.className='mt-1';wrap.innerHTML='<span class="badge badge-chiusa-v7" style="background:#1e8b3d">Chiusa</span>';td.appendChild(wrap);}}});['[data-field="dataScadenza"]','.data-scadenza','.col-scadenza'].forEach(sel=>document.querySelectorAll(sel).forEach(el=>el.classList.add('text-scadenza-rossa')));}catch(e){console.warn(LOG,"decorateList",e);}}
async function lista_v7(){try{if(window.__searchLock?.lock)window.__searchLock.lock();if(typeof pauseRealtime==="function")pauseRealtime();const F=getFilters();const hasAny=Object.keys(F).some(k=>has(F[k]));let data,error;if(!hasAny){({data,error}=await sb.from('records').select('*').order('dataApertura',{ascending:false}).limit(500));}else{({data,error}=await buildQuery(F));}if(error)throw error;const rows=clientExactFilter(Array.isArray(data)?data:[],F);if(typeof window.drawListPage==='function'){await window.drawListPage(rows);decorateList(rows);}if(window.__searchLock?.unlock)window.__searchLock.unlock();if(typeof resumeRealtime==="function")resumeRealtime();console.log(LOG,"OK",{rows:(rows||[]).length,F});}catch(e){console.error(LOG,e);if(window.__searchLock?.unlock)window.__searchLock.unlock();}}
function ensureResetButton(){const cercaBtn=document.querySelector("#btnDoSearch");if(!cercaBtn)return;if(document.getElementById("btnHardReset"))return;const wrap=cercaBtn.parentElement||cercaBtn.closest(".d-grid")||cercaBtn.parentNode;const btn=document.createElement("button");btn.id="btnHardReset";btn.type="button";btn.className="btn btn-outline-secondary ms-2";btn.textContent="Reset";btn.addEventListener("click",doReset);if(wrap&&wrap.appendChild)wrap.appendChild(btn);else cercaBtn.insertAdjacentElement("afterend",btn);}
function init(){const cercaBtn=document.querySelector("#btnDoSearch");if(cercaBtn){cercaBtn.removeEventListener("click",window.lista,true);cercaBtn.addEventListener("click",lista_v7,true);}const applyBtn=document.querySelector("#btnApplyFilters");if(applyBtn){applyBtn.removeEventListener("click",window.lista,true);applyBtn.addEventListener("click",lista_v7,true);}document.addEventListener("keydown",e=>{if(e.key==="Enter"&&document.activeElement&&document.activeElement.closest("#page-search")){lista_v7();}});const resetBtn=document.querySelector("#btnClearFilter")||document.querySelector("#btnReset");if(resetBtn)resetBtn.addEventListener("click",doReset);ensureResetButton();window.lista=lista_v7;console.log(LOG,"attivo: exact tecnico client-side, reset vicino Cerca, unificato");}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();})();